name: sync-node

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:   # 手动触发按钮

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # 推送镜像所需权限

    steps:
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: pull and push
        run: |
          docker pull docker.io/library/node:trixie && docker tag docker.io/library/node:trixie ghcr.io/vansour/node:trixie && docker push ghcr.io/vansour/node:trixie
